name: nakama-tictactoe
data_dir: /nakama/data

logger:
  level: DEBUG

console:
  port: 7351
  username: admin
  password: password

socket:
  port: 7350

session:
  cors_allowed_origins: 
    - "http://localhost:5173"